"""add user&profile

Revision ID: df7708eff5ab
Revises: 
Create Date: 2023-07-15 18:51:58.607373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7708eff5ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('sns_type', sa.Enum('guest', 'email', 'facebook', 'google', 'kakao', 'apple', name='snstype'), nullable=True),
    sa.Column('status', sa.Enum('inactive', 'active', 'blocked', 'deleted', name='userstatus'), nullable=True),
    sa.Column('withdrawal_reason', sa.String(length=255), nullable=True),
    sa.Column('last_service_used', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=10), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('accept_terms_agree', sa.Boolean(), nullable=True),
    sa.Column('marketing_agree', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
